openapi: 3.0.0
info:
  title: TicTacTrip Assignment
  version: 1.0.0
  description: API documentation for the TicTacTrip Assignment API
servers:
  - url: http://localhost:3000
paths:
  /api/token:
    post:
      summary: Authenticate User
      description: Returns a token for user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/justify :
    post:
      summary: Justify Text
      description: Returns a justified text
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      justifiedText:
                        type: string
            '400':
              description: Bad Request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '401':
              description: Unauthorized
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '402':
              description: Payment Required
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '403':
              description: Forbidden
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '404':
              description: Not Found
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '500':
              description: Internal Server Error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'




components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
